// routes/meetingRoutes.js
import express from 'express';
import { google } from 'googleapis';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const router = express.Router();

// 1. Setup paths for ES Modules (since __dirname doesn't exist in ESM)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TOKEN_PATH = path.join(__dirname, '../token.json');

// 2. Load Environment Variables
const CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI;

const oAuth2Client = new google.auth.OAuth2(CLIENT_ID, CLIENT_SECRET, REDIRECT_URI);
const SCOPES = ['https://www.googleapis.com/auth/calendar'];

// 3. Helper to load saved tokens
const loadToken = () => {
    try {
        if (fs.existsSync(TOKEN_PATH)) {
            const token = fs.readFileSync(TOKEN_PATH);
            oAuth2Client.setCredentials(JSON.parse(token));
            return true;
        }
        return false;
    } catch (err) {
        return false;
    }
};

// --- ROUTES ---

// Generate Google Auth URL
router.get('/auth/url', (req, res) => {
    const authUrl = oAuth2Client.generateAuthUrl({
        access_type: 'offline',
        scope: SCOPES,
    });
    res.json({ url: authUrl });
});

// Callback to save the token
router.get('/auth/callback', async (req, res) => {
    const { code } = req.query;
    try {
        const { tokens } = await oAuth2Client.getToken(code);
        oAuth2Client.setCredentials(tokens);
        fs.writeFileSync(TOKEN_PATH, JSON.stringify(tokens));
        res.send('Authentication successful! You can close this tab.');
    } catch (error) {
        console.error('Error retrieving access token', error);
        res.status(500).send('Authentication failed');
    }
});

// Create Meeting Logic
router.post('/create-meeting', async (req, res) => {
    if (!loadToken()) {
        return res.status(401).json({ error: 'User not authenticated' });
    }

    const calendar = google.calendar({ version: 'v3', auth: oAuth2Client });

    // Set meeting time (Start Now, End in 1 hour)
    const eventStartTime = new Date();
    const eventEndTime = new Date();
    eventEndTime.setHours(eventEndTime.getHours() + 1);

    const event = {
        summary: 'HR Interview',
        description: 'Generated by HRMS System',
        start: { dateTime: eventStartTime, timeZone: 'Asia/Kolkata' },
        end: { dateTime: eventEndTime, timeZone: 'Asia/Kolkata' },
        conferenceData: {
            createRequest: {
                requestId: `meet-${Date.now()}`,
                conferenceSolutionKey: { type: 'hangoutsMeet' },
            },
        },
    };

    try {
        const response = await calendar.events.insert({
            calendarId: 'primary',
            resource: event,
            conferenceDataVersion: 1,
        });

        res.json({
            status: 'success',
            link: response.data.hangoutLink,
        });
    } catch (error) {
        console.error('Error creating meeting:', error);
        res.status(500).json({ error: 'Failed to create meeting' });
    }
});

export default router;